###########
# site.url, site.title

title: 'DeafChi'
description: 'The central hub in Chicago for the d/Deaf'
author: 'Chicago Deaf Techies'

## note:
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
url:  'https://deafchi.com'
enforce_ssl: 'deafchi.com'
copyright: 'Copyright &copy; 2017 DeafChi. All Rights Reserved.'
credits: 'Credits: made with love using Twitter Bootstrap.'

######## Social Settings
social:
  -
    name: facebook
    icon: facebook-square
    url: '#'
  -
    name: twitter
    icon: twitter-square
    url: '#'

  -
    name: instagram
    icon: instagram
    url: '#'

  -
    name: slack
    icon: slack
    url: '#'

  -
    name: github
    icon: github-square
    url: '#'

########
# more settings

collections:
  people:
    output: true
    permalink: /conversations/:path

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.rst
- Gemfile.lock
- css/bootstrap

safe: true
lsi: false
